### ISSUE TITLE
On hotstart of the app, current state from server should be requested

### ISSUE THREAD

**Issue by AnSch1510** [MaSch0212/minigolf-friday#110]
When I have the app open on the current event and bring it to the background, after a reopen, I everyone have to switch the page to get the actual information from the server

**Comment by MaSch0212** [comment]
The state is invalidated when the connection resets. So normally this should already work. Can you reproduce this?

**Comment by AnSch1510** [comment]
It appears every time I open the app. Sometimes when I go back and back to the event, it has a player registered which was not visible previously
