### ISSUE TITLE
remove fallback timeslot not possible

### ISSUE THREAD

**Issue by AnSch1510** [MaSch0212/minigolf-friday#120]
current workaround is: remove registration of 21:00 timeslot and register again

**Comment by MaSch0212** [comment]
What is the issue? Normally there should be an "x" in them dropdown control to clear the fallback.

**Comment by AnSch1510** [comment]
it is visible, but once you click on it, it will revert to the last chosen time.

tested on edge and ios

**Comment by MaSch0212** [comment]
Hm, okay that seems to be a server issue then. Do you see any errors in the browser console?

**Comment by AnSch1510** [comment]
no issues 
![image](https://github.com/MaSch0212/minigolf-friday/assets/9435005/64ad0c9d-ebc7-4f1f-93d0-9ce103a0d05c)
