### ISSUE TITLE
Improve "create user" process

### ISSUE THREAD

**Issue by AnSch1510** [MaSch0212/minigolf-friday#134]
When -on iOS- creating a user, it first has to be created, after that one has to find it again to click on the edit button and then on the get Passwort button and then on the copy button.

Maybe we should, after creating a user, not close the window but add a button to copy a pre defined "welcome" text to the clipboard.

Then we could create a user, klick the "copy welcome" button, send it to the new user via messenger, copy the password and send it as a separate message to the user via messenger.

The password should be send as a separate message, so the user can easily copy only the Passwort to insert it to the app to log in.

Previously I've send the following message:

Hallo Liebe Minigolffreunde!
Die Anmeldung zum Minigolffreitag läuft ab jetzt über die Web-basierte App, welche du unter:
https://minigolf.anschnet.de
aufrufen kannst.
Speichere sie dir als Lesezeichen, oder füge sie zu deinem Home-Bildschirm hinzu um jederzeit darauf zugreifen zu können.
Melde dich dort bitte mit deinem Passwort an und registriere dich selber für deine Spielzeiten.
Bitte schreibe doch trotzdem im Facebook Beitrag, dass du dich registriert hast, damit dort die Konversation aufrecht erhalten wird.
Viel Spaß beim Minigolfen!
Dein Orga-Team

**Comment by MaSch0212** [comment]
When creating a user, the password is already automatically copied to the clipboard 🤔

**Comment by MaSch0212** [comment]
But yeah, maybe we can open a different dialog when creating a user with two buttons:
- Copy welcome message
- Copy Password

**Comment by AnSch1510** [comment]
> When creating a user, the password is already automatically copied to the clipboard 🤔

Not really.
It shows the dialog which says that it will copy the password, but nothing is actually being copied 😐

**Comment by MaSch0212** [comment]
yeah on iOS you need to copy the text manually as copy to clipboard needs to be done during a user event. In the currentl implementation it is done after the server response. With an extra dialog we can solve this, as the button presses are user events.
