### ISSUE TITLE
Indicate registration was successully saved

### ISSUE THREAD

**Issue by AnSch1510** [MaSch0212/minigolf-friday#14]
Lieber André, hat geklappt, aber noch geht die Anmeldung über den Facebookbutton nicht. Bei der Terminauswahl wäre gut, wenn man unten einen Button hat mit bestätigen oder weiter, was einen dann zu der Seite zurückführt, wo steht, dass man zwei Termine ausgewählt hat. So wie bisher trägt man die Termine ein durch auswählen und sieht aber nicht, ob es erfasst ist oder nicht. Ist eine Idee, damit man Bescheid weiß, dass es geklappt hat. Aber ansonsten ist es total simpel und cool

**Comment by MaSch0212** [comment]
To summarize this issue: There should be an indicator on the registration page of an event that the registration was actually saved successfully.

**Comment by AnSch1510** [comment]
something linke this maybe - which will fade out after 1 second

![Screenshot 2024-06-07 111206](https://github.com/MaSch0212/minigolf-friday/assets/9435005/6329f187-beea-404c-bfc5-79079a6639ab)
