### ISSUE TITLE
Beim Anmeldebildschirm kommt man mit der Return Taste nicht vom E-Mail- aufs Passwort Feld

### ISSUE THREAD

**Issue by AnSch1510** [MaSch0212/minigolf-friday#16]

**Comment by MaSch0212** [comment]
Du möchtest mit der Return Taste (NumPad Enter) vom E-Mail Feld ins Passwort Feld wechseln?
Dafür gibt es doch eigentlich Tab. Mit Return oder Enter sollte die Form abgeschickt werden (also der Login angestoßen werden)

**Comment by AnSch1510** [comment]
Auf dem iPhone gibt's kein tab. Da ist es bei vielen Seiten so, dass ich den Benutzer eintrage, enter drücke, dann das Passwort und beim weiteren enter wird man dann tatsächlich eingeloggt

**Comment by AnSch1510** [comment]
Muss aber auch nicht sein ☺️

**Comment by MaSch0212** [comment]
Closed, as we changed the authentication model to just a random password.
