### ISSUE TITLE
Nutzerhinweis

### ISSUE THREAD

**Issue by AnSch1510** [MaSch0212/minigolf-friday#17]
![image](https://github.com/MaSch0212/minigolf-friday/assets/9435005/109e270f-7b66-4d5d-b04d-7f1e4f7d0fc3)

**Comment by AnSch1510** [comment]
![image](https://github.com/MaSch0212/minigolf-friday/assets/9435005/5b268526-a48b-40bf-8e80-d8f7d6b24146)

**Comment by MaSch0212** [comment]
Probably related to #4

**Comment by MaSch0212** [comment]
Fixed by #21
