### ISSUE TITLE
Players should be able to see which players have registered for each timeslot

### ISSUE THREAD

**Issue by AnSch1510** [MaSch0212/minigolf-friday#19]
Es ist gewünscht, dass man sehen kann wer sich bisher für welchen Zeitslot angemeldet hat. Wäre dann so wie bisher bei den Facebook Kommentaren.

**Comment by MaSch0212** [comment]
Soll das dan pro Zeitslot angezeigt werden, oder nur wer sich grundsätzlich an dem event angemeldet at (egal welcher Zeitslot)?

**Comment by AnSch1510** [comment]
Ich wäre dafür, dass man sehen kann, wer sich bei welchem Zeitslot angemeldet hat. Bisher sieht man das bei der Anmeldung bei Facebook im Anmelde-Kommentar auch

**Comment by MaSch0212** [comment]
As discussed: A table should be displayed below the registration settings where each row is a player and each timeslot is a column.
