### ISSUE TITLE
Add event time is in ugly format

### ISSUE THREAD

**Issue by AnSch1510** [MaSch0212/minigolf-friday#32]
![image](https://github.com/MaSch0212/minigolf-friday/assets/9435005/00684bdf-0696-47c9-bb9a-36e490f5baad)

I would prefer to use the TT-MM-YYYY format instead of the MM/TT/YYYY

**Comment by MaSch0212** [comment]
Currently only the default translations from PrimeNG are used (which include date formats).
German translations should be loaded if German is selected.
