### ISSUE TITLE
add missing dependencies

### ISSUE THREAD

**Issue by AnSch1510** [MaSch0212/minigolf-friday#35]
pnpm has to be installed aswell

**Comment by MaSch0212** [comment]
This should not be necessary when corepack is enabled `corepack enable`.

**Comment by AnSch1510** [comment]
https://pnpm.io/installation

**Comment by AnSch1510** [comment]
> This should not be necessary when corepack is enabled `corepack enable`.

I dont know how to enable corepack - during installation i've checked everything

**Comment by MaSch0212** [comment]
After installing node.js start a new terminal and run `corepack enable`.
