### ISSUE TITLE
Move focus to first text field when creating a new item

### ISSUE THREAD

**Issue by AnSch1510** [MaSch0212/minigolf-friday#42]
If I want to create a new course, I first klick on "create" then into the text field to enter the name.

This clicking into the text field should be not necessary to gain focus

**Comment by MaSch0212** [comment]
This is actually implemented already. Apple seems to dislike it though that websites auto-focus input fields, so it does not work on iPhone:
- https://medium.com/@brunn/autofocus-in-ios-safari-458215514a5f
- https://stackoverflow.com/questions/5771785/how-can-you-autofocus-on-a-form-field-in-iphone-safari
