### ISSUE TITLE
Add reload buttons

### ISSUE THREAD

**Issue by MaSch0212** [MaSch0212/minigolf-friday#55]
When the app is installed on a mobile device, the only way to reload the data is to force close the app and reopen it, as there is no browser frame displayed.
Therefore each page, should have its own reload button, to refresh the data of the currently visible view.

**Comment by AnSch1510** [comment]
Isn't there the feature planed to push changes to the clients. This would make a refresh button obsolete

**Comment by MaSch0212** [comment]
Yes, but that is not high priority. The refresh button is very easy to implement, so it is good as a temporary solution.
