### ISSUE TITLE
Add "add to homescreen button"

### ISSUE THREAD

**Issue by AnSch1510** [MaSch0212/minigolf-friday#68]
https://gist.github.com/guillaumegarcia13/64eb3098428972b7cd444b519c3e859e

Maybe we could add a button to install the app onto the homescreen. So that the unser don't have to go through the menu

**Comment by AnSch1510** [comment]
https://web.dev/articles/customize-install?hl=de

**Comment by MaSch0212** [comment]
This is not available on iOS: https://developer.mozilla.org/en-US/docs/Web/API/BeforeInstallPromptEvent

**Comment by AnSch1510** [comment]
ok, then there should be some kind of explanation on how to install the app onto the home screen. either by pointing in the direction of the share button (if the browser is known) or by providing a website which explains how to do it

**Comment by AnSch1510** [comment]
will be done in #58
