### ISSUE TITLE
As admin, see what notification settings a user has performed

### ISSUE THREAD

**Issue by AnSch1510** [MaSch0212/minigolf-friday#84]
It would be good to see if a user has permissions enabled and on which devices. Maybe with a button to send a test notification to this specific device

**Comment by MaSch0212** [comment]
Why is this needed?

**Comment by AnSch1510** [comment]
Maybe just add a notification button with a text input next to it. Then we could "message" someone with a custom text. If someone doesn't have Facebook for example. Then that would be the only way to reach out to someone

**Comment by MaSch0212** [comment]
But this would be a one-way only communication, right? The user cannot answer a notification message.

**Comment by MaSch0212** [comment]
What would this be used for? Just want to understand 😉

**Comment by AnSch1510** [comment]
My first thought would be just for debugging purposes.
May a user claims he does not receive notifications. With this we would be able to send a test notification to just this user
