### ISSUE TITLE
When player do a logout, the notifications should disable

### ISSUE THREAD

**Issue by AnSch1510** [MaSch0212/minigolf-friday#85]
Currently if a player (A) does a logout, the notification settings persist. When an other player (B) logs in with the same "app" the notifications are still enabled for player A and player B is not able to enable it. Actually I don't know exactly what the behavior is in that case.

**Comment by MaSch0212** [comment]
The idea was that the same subscription is switched to the newly logged in user. But I agree, we should unsubscribe the notification url when logging out and subscribing again if logged in.
