### ISSUE TITLE
Start Event is not possible

### ISSUE THREAD

**Issue by AnSch1510** [MaSch0212/minigolf-friday#87]
![image](https://github.com/MaSch0212/minigolf-friday/assets/9435005/0f826fcd-59ad-44db-92c2-5d95eacd5334)

I'm not able to klick on the start event button.

**Comment by AnSch1510** [comment]
I'm dump - I did not supply the map information for the event - maybe we should include a information why it is not able to start

**Comment by MaSch0212** [comment]
Yeah, I guess a small text below the button would be sufficient.
