### ISSUE TITLE
unsubscribe from push does not actually delete the database entry

### ISSUE THREAD

**Issue by AnSch1510** [MaSch0212/minigolf-friday#89]
when sending a delete to `/api/notifications` with the payloat `{"endpoint": "test"}` the value test will not be received by the server. it will return `Error: response status is 400` -> `"reason": "'Endpoint' darf nicht leer sein."`

**Comment by MaSch0212** [comment]
Hm, maybe the endpoint should be part of the URL. Either a path segment or query parameter. Not sure if request bodies work correctly for delete requests out of the box.

**Comment by AnSch1510** [comment]
Maybe we could identify a endpoint with a self generated id. Then we just have to include this id to the uri instead of the whole endpoint string

**Comment by MaSch0212** [comment]
I thought about this, but then I need to go to the sever to get the id. End endpoint itself is unique, so there is not really a need for a generated id on our side.

**Comment by MaSch0212** [comment]
I was worried that the endpoint link inside a query parameter would make the URL too long. There are limits as well.
Found out that the FastEndpoints library we use for hosting endpoints is using "*/*" as the content-type per default, so I just needed to set "application/json" and it worked.
